import Button from "../Button.jsx";

// "What matters most" — the app's read on the gap between the two lives, drawn
// from the focus lines (generated by comparing the current and aspirational
// obituaries). Also home to the (future) gentle-reminder system.
export default function WhatMattersMost({ focusLines, onBack }) {
  const lines = focusLines?.length ? focusLines : [];

  return (
    <div className="flex flex-1 flex-col items-center animate-fadein">
      <p className="mb-6 text-xs uppercase tracking-[0.35em] text-ember-400/70">
        What matters most
      </p>
      <p className="mb-14 max-w-md text-center font-body text-ash-300">
        The distance between the life you're living and the life you could — this
        is where to begin.
      </p>

      {lines.length > 0 ? (
        <ul className="flex w-full max-w-xl flex-col gap-6">
          {lines.map((line, i) => (
            <li
              key={i}
              className="text-center font-body text-xl leading-relaxed text-cream-200 animate-fadeup"
              style={{ animationDelay: `${i * 140}ms` }}
            >
              {line}
            </li>
          ))}
        </ul>
      ) : (
        <p className="font-body text-ash-400">
          Your focus lines will appear here.
        </p>
      )}

      {/* Future: gentle reminders toward what matters */}
      <div className="mt-20 w-full max-w-md border-t border-ash-600/50 pt-10 text-center">
        <p className="font-body text-ash-300">
          Soon, Working Backwards will gently remind you of what matters — a quiet
          nudge toward the life you chose.
        </p>
        <button
          type="button"
          disabled
          title="Coming soon"
          className="mt-5 cursor-not-allowed rounded-full border border-ash-600 px-5 py-2.5 text-xs uppercase tracking-[0.2em] text-ash-500"
        >
          Set up reminders (coming soon)
        </button>
      </div>

      <div className="mt-14">
        <Button variant="quiet" onClick={onBack}>
          Back
        </Button>
      </div>
    </div>
  );
}
